apiVersion: vista.fortiminds.io/v1
businessApplication:
  criticality: Tier2
  id: c34826a7-ee4a-4189-890e-24e735760249
  name: test_fm_001
governance:
  enforced: true
  policies:
    - VISTA-CONTEXT-001
kind: RepositoryManifest
metadata:
  organisation: testveracode
  repository: test_003
scanners:
  - enabled: false
    name: veracode
